# Generated by Django 4.2.19 on 2025-02-27 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=15)),
                ('class_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_images/')),
                ('face_encoding', models.BinaryField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=50)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
