# Generated by Django 4.2.19 on 2025-04-05 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=15)),
                ('class_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/student_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('present_days', models.IntegerField(default=0)),
                ('full_day_present', models.IntegerField(default=0)),
                ('half_day_present', models.IntegerField(default=0)),
                ('half_day_absent', models.IntegerField(default=0)),
                ('full_day_absent', models.IntegerField(default=0)),
                ('remaining_leave_days', models.IntegerField(default=27)),
                ('percentage', models.FloatField(default=0.0)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10)),
                ('period', models.CharField(choices=[('1st_hour', '1st Hour'), ('2nd_hour', '2nd Hour'), ('3rd_hour', '3rd Hour'), ('4th_hour', '4th Hour'), ('5th_hour', '5th Hour')], max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
