# Generated by Django 4.2.19 on 2025-04-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentimage',
            old_name='reg_no',
            new_name='student',
        ),
    ]
