# Generated by Django 4.2.19 on 2025-03-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentimage',
            name='face_encoding',
            field=models.TextField(),
        ),
    ]
