# Generated by Django 4.2.19 on 2025-03-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_student_reg_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='face_encoding',
            field=models.TextField(max_length=255),
        ),
    ]
