# Generated by Django 4.2.19 on 2025-03-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_studentimage_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentimage',
            name='face_encoding',
        ),
    ]
