# Generated by Django 4.2.19 on 2025-03-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_studentimage_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.ImageField(upload_to='media/student_images/'),
        ),
    ]
