# Generated by Django 4.2.19 on 2025-03-05 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_studentimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.CharField(choices=[('1st_hour', '1st Hour (8:45 - 9:40)'), ('2nd_hour', '2nd Hour (9:45 - 10:40)'), ('3rd_hour', '3rd Hour (10:45 - 11:40)'), ('4th_hour', '4th Hour (12:20 - 1:15)'), ('5th_hour', '5th Hour (1:20 - 2:15)')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10),
        ),
    ]
