# Generated by Django 4.2.19 on 2025-03-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_period_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='period',
            field=models.CharField(choices=[('1st_hour', '1st Hour'), ('2nd_hour', '2nd Hour'), ('3rd_hour', '3rd Hour'), ('4th_hour', '4th Hour'), ('5th_hour', '5th Hour')], max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10),
        ),
    ]
