# Generated by Django 4.2.19 on 2025-03-07 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_period_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('present', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('leave', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('fine', models.FloatField(default=0.0)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='attendance.student')),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_phone', to='attendance.student')),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='attendance.student')),
                ('sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='attendance.student')),
            ],
        ),
    ]
