# Generated by Django 4.2.19 on 2025-03-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='fine',
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports_class', to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='phone_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports_phone', to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports_reg_no', to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports_sname', to='attendance.student'),
        ),
    ]
