# Generated by Django 4.2.19 on 2025-03-31 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_attendancereport_fine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancereport',
            old_name='absent',
            new_name='full_day_absent',
        ),
        migrations.RenameField(
            model_name='attendancereport',
            old_name='leave',
            new_name='full_day_present',
        ),
        migrations.RenameField(
            model_name='attendancereport',
            old_name='present',
            new_name='half_day_absent',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='sname',
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='half_day_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='remaining_leave_days',
            field=models.IntegerField(default=27),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
    ]
